// Emits a fixture encrypted by the *browser* implementation, for the Flutter
// app's test suite to decrypt.
//
// The two implementations of TJE1 are the only thing standing between a memory
// written on the website and one that opens in the app. A round-trip test
// inside either codebase proves nothing about the pair — this crosses the gap
// for real. Regenerate with:
//
//   npx tsx scripts/emit-crypto-fixture.mts \
//     "<phone-app-repo>/test/fixtures/website_encrypted.json"

import { writeFileSync, mkdirSync } from 'fs'
import { dirname, resolve } from 'path'
import { deriveKeys, encryptFile, encryptText } from '../src/lib/crypto'

// A fixed data key, so the fixture is reproducible and a failure is not a
// coin flip. Exactly the bytes the Dart test derives from.
const dek = new Uint8Array(32)
for (let i = 0; i < 32; i++) dek[i] = (i * 7 + 3) & 0xff

const out = process.argv[2]
if (!out) throw new Error('usage: emit-crypto-fixture.mts <output.json>')

const keys = await deriveKeys(dek)

const texts = [
  'Happy birthday, my love.',
  '{"lat":"51.5072","lon":"-0.1276","name":"London, England"}',
  'https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT',
  'emoji 🎂 and accents é ü ß',
]

// Sizes chosen to straddle the chunk boundary the container uses, since that
// is where an off-by-one between the two implementations would hide.
const CHUNK = 1 << 20
const sizes = [0, 1, 1000, CHUNK - 1, CHUNK, CHUNK + 1]

function pattern(n: number): Uint8Array {
  // xorshift32, mirrored exactly in the Dart test. Deliberately shift-and-xor
  // only: a multiplicative generator overflows JavaScript's 53-bit mantissa
  // and quietly diverges from the same arithmetic in Dart's 64-bit ints, which
  // would look like a decryption failure rather than a test bug.
  const b = new Uint8Array(n)
  let x = 0x2545f491
  for (let i = 0; i < n; i++) {
    x ^= (x << 13) >>> 0
    x >>>= 0
    x ^= x >>> 17
    x ^= (x << 5) >>> 0
    x >>>= 0
    b[i] = x & 0xff
  }
  return b
}

const files: { size: number; container: string }[] = []
for (const size of sizes) {
  const blob = await encryptFile(new Blob([pattern(size)]), keys.file)
  files.push({
    size,
    container: Buffer.from(await blob.arrayBuffer()).toString('base64'),
  })
}

mkdirSync(dirname(resolve(out)), { recursive: true })
writeFileSync(
  resolve(out),
  JSON.stringify(
    {
      note: 'Generated by the website. See scripts/emit-crypto-fixture.mts.',
      dek: Buffer.from(dek).toString('base64'),
      texts: await Promise.all(
        texts.map(async plain => ({
          plain,
          sealed: await encryptText(plain, keys.text),
        })),
      ),
      files,
    },
    null,
    2,
  ) + '\n',
)
console.log(`wrote ${out}`)
