#!/usr/bin/env bash
#
# Self-hosts the two web fonts, so visitors' IP addresses stop being sent to
# Google on every page view. German courts have held that serving Google Fonts
# from Google's servers without consent is unlawful; self-hosting removes the
# question rather than documenting it.
#
# Run once, from anywhere:   bash scripts/self-host-fonts.sh
#
# It downloads the exact weights the site uses, writes src/fonts.css, wires
# that into main.tsx, and removes the Google <link> tags from index.html.
# Idempotent: safe to run again after a font change.
#
# It needs network access to fonts.googleapis.com — which is why this is a
# script and not part of the commit that created it.

set -euo pipefail
cd "$(dirname "$0")/.."

OUT_DIR="public/assets/fonts"
CSS_OUT="src/fonts.css"
# A modern browser UA is required, or Google serves legacy TTF instead of woff2.
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
API="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400;1,500&family=Montserrat:wght@300;400;500;600&display=swap"

mkdir -p "$OUT_DIR"

echo "Fetching font stylesheet…"
css=$(curl -sfL -A "$UA" "$API") || { echo "Could not reach fonts.googleapis.com" >&2; exit 1; }

echo "Downloading font files…"
: > "$CSS_OUT"
{
  echo "/* Self-hosted web fonts. Generated by scripts/self-host-fonts.sh —"
  echo "   re-run that script rather than editing this file by hand. */"
  echo
} >> "$CSS_OUT"

count=0
# Walk each @font-face block, download its woff2, and rewrite the src to a
# local path so no request reaches Google at runtime.
while IFS= read -r block; do
  url=$(grep -oE 'https://fonts\.gstatic\.com[^)]+\.woff2' <<< "$block" || true)
  [ -z "$url" ] && continue
  family=$(grep -oE "font-family: '[^']+'" <<< "$block" | head -1 | sed "s/font-family: '//;s/'//")
  weight=$(grep -oE 'font-weight: [0-9]+'   <<< "$block" | head -1 | grep -oE '[0-9]+')
  style=$(grep -oE 'font-style: [a-z]+'     <<< "$block" | head -1 | awk '{print $2}')
  slug=$(tr '[:upper:] ' '[:lower:]-' <<< "$family")
  file="${slug}-${weight}-${style}.woff2"

  curl -sfL -A "$UA" "$url" -o "$OUT_DIR/$file"
  count=$((count + 1))

  {
    echo "@font-face {"
    echo "  font-family: '$family';"
    echo "  font-style: $style;"
    echo "  font-weight: $weight;"
    echo "  font-display: swap;"
    echo "  src: url('/assets/fonts/$file') format('woff2');"
    echo "}"
    echo
  } >> "$CSS_OUT"
done < <(awk 'BEGIN{RS="@font-face"} NR>1{print "@font-face" $0}' <<< "$css")

echo "Downloaded $count font files into $OUT_DIR"

# Wire the stylesheet in, and take the Google tags out.
python3 - <<'PY'
import pathlib, re

main = pathlib.Path('src/main.tsx'); s = main.read_text()
if "./fonts.css" not in s:
    s = s.replace("import './index.css'", "import './fonts.css'\nimport './index.css'")
    main.write_text(s)
    print("main.tsx: imports fonts.css")
else:
    print("main.tsx: already wired")

idx = pathlib.Path('index.html'); h = idx.read_text()
before = h
h = re.sub(r'\n *<!-- Font Preconnect for Performance -->', '', h)
h = re.sub(r'\n *<link rel="preconnect" href="https://fonts\.(googleapis|gstatic)\.com"[^>]*>', '', h)
h = re.sub(r'\n *<link href="https://fonts\.googleapis\.com/css2[^"]*" rel="stylesheet">', '', h)
if h != before:
    idx.write_text(h)
    print("index.html: Google Fonts tags removed")
else:
    print("index.html: already clean")
PY

echo
echo "Done. Run 'npm run build' and check the site still renders in Cormorant Garamond and Montserrat."
